---
title: "Normative Conformity"
author: "Tim Wilson"
date: today
format:
  revealjs:
    theme: [default, styles.scss]
    menu: false
    progress: false
    history: false
    transition: fade
    transition-speed: fast
    incremental: false
    logo: images/meadowlark-logo.png
    width: 1920
    height: 1080
    margin: 0.05
    highlight-style: github
    center: false
title-slide-attributes:
  data-visibility: "hidden"
execute:
  echo: false
  warning: false
  message: false
---

# Why are so many slide decks<br>[so bad]{.emphasis}? {background-color="var(--divider-bg)"}


## {.center}
::: {.slide-body-heading}
normative conformity
:::
::: {style = "font-size: 1.6em; color: #317168; margin-top: -0.8em"}
**nor**-muh-tiv   kuhn-**for**-muh-tee
:::

> "the tendency of individuals to adjust their behavior, attitudes, or beliefs to align with the perceived standards or expectations of a group or society"

::: {.slide-source-footer .muted}
Source: https://lifestyle.sustainability-directory.com/area/normative-conformity/
:::

## {.center}
::: {.slide-body-heading}
normative conformity
:::
::: {style = "font-size: 1.6em; color: #317168; margin-top: -0.8em"}
**nor**-muh-tiv   kuhn-**for**-muh-tee
:::

> "the tendency of individuals to adjust their [presentations]{.emphasis} to align with the perceived standards of their [organization or industry]{.emphasis}"


## normative conformity…illustrated {.statement}

"This slide deck is killing me."

. . .

"Let me produce another one."


## {.center background-image="images/pic_uncle_sam_beige.png" background-size="auto 100%" background-position="right center"}

::: {.text-panel-left-60}
::: {.slide-body-heading}
[You]{.emphasis} have the power to [change]{.emphasis}!
:::
:::

::: {.notes}
Uncle Sam-like pic, full bleed to the right.

Then choose your own adventure with what you want to learn more about.
:::
